Enhancement/skale 3399 handle script error
skalenetwork/node-cli pull request #347
Opened 2020-11-04 13:00 UTC by badrogger

2020-11-04 17:25 UTC, dmitry-tk requested changes

2020-11-04 17:25 UTC, dmytrotkk commented on README.md
> +2.  [CLI usage](#cli-usage)
return spaces plz

2020-11-04 17:25 UTC, dmytrotkk commented on cli/node.py
> +              help="Skaip mysql backup")
Typo here

2020-11-04 19:49 UTC, badrogger commented on cli/node.py
> +              help="Skaip mysql backup")
addressed

2020-11-04 19:49 UTC, badrogger commented on README.md
> +2.  [CLI usage](#cli-usage)
addressed

2020-11-05 09:10 UTC, dmitry-tk approved these changes

2020-11-05 09:10 UTC, merged