SKALE-4124 Add gas limit and gas price to set domain cmd
skalenetwork/node-cli pull request #540
Opened 2021-09-30 17:07 UTC by dmitry-tk

2021-10-04 10:34 UTC, badrogger requested changes

2021-10-04 10:34 UTC, badrogger commented on node_cli/cli/node.py
> +    help='Gas limit for registration transaction'
typo: "registration transaction" -> "set domain transaction"

2021-10-04 10:39 UTC, dmitry-tk commented on node_cli/cli/node.py
> +    help='Gas limit for registration transaction'
fixed, thanks!

2021-10-04 10:42 UTC, badrogger approved these changes

2021-10-06 10:54 UTC, badrogger requested changes

2021-10-06 10:54 UTC, badrogger commented on text.yml
> +gas_price:
Looks like this lines can be removed to

2021-10-06 13:45 UTC, dmitry-tk commented on text.yml
> +gas_price:
done

2021-10-06 13:47 UTC, badrogger approved these changes

2021-10-15 14:02 UTC, merged