Use nftables to configure firewall
skalenetwork/node-cli pull request #800
Opened 2024-11-18 19:55 UTC by badrogger

2024-12-23 13:29 UTC, dmytrotkk requested changes

2024-12-23 13:29 UTC, dmytrotkk commented on node_cli/core/nftables.py
> +        logger.error(f'Unable to import iptc due to an error {err}')
should be `Unable to import nftables...` instead of `iptc`

2024-12-23 13:29 UTC, dmytrotkk commented on node_cli/operations/__init__.py
> +    configure_nftables as configure_firewall
what is the point of exporting this function under a different name here?

it is used 6 times as `configure_nftables` and 1 time as `configure_firewall` - suggesting keeping just one version for consistency.

2024-12-23 13:29 UTC, dmytrotkk commented on node_cli/core/node.py
> +    if (__version__ == 'test' or __version__.startswith('2.6')) and prev_version == '2.5.0':
will it work ok if `migrate` will be executed multiple times? (let's say for 2.6.1, 2.6.2, etc)

2024-12-23 13:29 UTC, dmytrotkk commented on node_cli/migrations/focal_to_jammy.py
> +import logging
no license header

2024-12-23 13:29 UTC, dmytrotkk commented on node_cli/utils/helper.py
> +def remove_between_brackets(text: str, pattern: str) -> str:
confusing name - maybe let's use a small docstring with a function explanation?

2024-12-23 16:55 UTC, dmytrotkk approved these changes

2024-12-26 17:41 UTC, DmytroNazarenko approved these changes

2024-12-30 17:06 UTC, dmytrotkk commented on node_cli/core/node.py
> +    if not sync_node and (not is_admin_running() and not is_api_running()):
after the latest fix, redundant braces can be removed:

```python
if not sync_node and not is_admin_running() and not is_api_running():
```

2024-12-30 17:07 UTC, dmytrotkk approved these changes

2024-12-30 17:27 UTC, merged